name: Changelog

on:
  push:
    branches: ["master"]
    paths-ignore: ["CHANGELOG.md"]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: "📥 Check-out"
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.AUTOMATION_REPO_TOKEN }}
      - name: "✏️ Generate release changelog"
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          onlyLastTag: false
          stripHeaders: false
          stripGeneratorNotice: true
          pullRequests: false
          unreleased: true
          issues: true
          prWoLabels: false
          issuesWoLabels: true
          addSections: '{"documentation":{"prefix":"**Documentation:**","labels":["documentation"]}}'
      - name: Temporarily disable branch protection
        uses: benjefferies/branch-protection-bot@master
        with:
          access-token: ${{ secrets.AUTOMATION_REPO_TOKEN }}
          enforce_admins: false
      - name: Push Changelog
        run: |
          set -e
          git config user.name 'Automatic Changelog'
          git config user.email '<github-actions@users.noreply.github.com>'
          tac CHANGELOG.md | awk 'NF {p=1} p' | tac > CHANGELOG.new
          mv CHANGELOG.new CHANGELOG.md
          git add CHANGELOG.md
          git commit -m 'Update Changelog' || :
          git push
      - name: Enable branch protection
        uses: benjefferies/branch-protection-bot@master
        if: always()  # Force to always run this step to ensure "include administrators" is always turned back on
        with:
          access-token: ${{ secrets.AUTOMATION_REPO_TOKEN }}
          enforce_admins: true
